# Generated by Django 4.2.2 on 2025-02-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_message_user_message_addressee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
