# Generated by Django 4.2.2 on 2024-09-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0003_category_image_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.DateField(verbose_name="Год выпуска"),
        ),
    ]
