# Generated by Django 4.2.2 on 2025-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_car_owner_alter_car_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="message_for_owner",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение владельцу"
            ),
        ),
    ]
